config/routes.rb
Rails.application.routes.draw do
  devise_for :users

get '/links' => 'links#index'
get '/links/new' => 'links#new'
post '/links' => 'links#create' 
get '/links/:id' => 'links#show'

  devise_scope :user do
   authenticated :user do
     root 'links#index', as: :authenticated_root
   end

   unauthenticated do
     root 'devise/registrations#new', as: :unauthenticated_root
   end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :visits

  def visit_count
   visits.count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController 

  def index
    @links = current_user.links
  end  

  def show
    @link = Link.find_by(:id => params[:id], :user_id => current_user.id)

    unless @link
      flash[:warning] = "Link not found"
      redirect_to links_path
    end
  end 

  def new
    @link = Link.new
  end 

  def create 
    @link = Link.new(
      :slug => params[:slug], 
      :target_url => params[:target_url], 
      :user_id => current_user.id
      )

    @link.standardize_target_url!

      if @link.save
        flash[:success] = "Link created successfully"
        redirect_to links_path
      else
        render 'new'
      end
    end  

    def edit
    end 

    def update
    end 




end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def create
    @link = Link.find_by(:slug => params[:slug])

    if @link
      Visit.create(:link_id => @link.id, :ip_address => request.remote_ip)
      redirect_to "http://#{@link.target_url}"
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortenerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!DOCTYPE html>
  <html>
  <head>
    <title>UrlShortenerApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid" id="main-navbar">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a id="logo" class="navbar-brand" href="/">url.co</a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="options-nav">Options<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if current_user.nil? %>
                  <li><a href="/users/sign_up">Sign Up</a></li>
                  <li><a href="/users/sign_in">Sign In</a></li>
                <% end %>
                
                <% if current_user %>
                  <li><a href="/users/edit">Edit Profile</a></li>
                  <li class="divider"></li>
                  <li><a href="/users/sign_out" id="sign_out_link">Sign Out</a></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  <div class="container-fluid">

    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "alert alert-#{name}" %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

  <% flash.each do |name, message| %>
  <div class="alert alert-<%= name %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/links/create.html.erb
create.html.erb

app/views/links/index.html.erb
<h1> Here are your links </h1>

<table>
  <tr>
    <th>Slug</th>
    <th>Target URL</th>
    <th>Created At</th>
    <th>Actions</th>
  </tr>
  <% @links.each do |link| %>
    <tr>
      <td><%= link.slug %></td>
      <td><%= link.target_url %></td>
      <td><%= link.created_at %></td>
      <td><%= link_to "Edit", edit_link_path(link.id) %> <%= link_to "Delete", link_path(link.id), :method => "delete", :data => {:confirm => "Are you sure you would like to delete the link: #{link.slug}?"} %></td>
    </tr>
  <% end %>
<table>

app/views/links/new.html.erb
h1>Create a new link</h1>

<% if @link.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
 
    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag "/links" do %>
  <%= label_tag :slug %>
  <%= text_field_tag :slug, @link.slug %>

  <%= label_tag :target_url %>
  <%= text_field_tag :target_url, @link.target_url %>

  <%= submit_tag "Create Link" %>
<% end %>

app/views/links/show.html.erb
<h1>Link Stats for <%= @link.slug%></h1>
<h3>Visits: <%= @link.visit_count %></h3>